- README.md
@tomkralidis , please review this improved overview and merge if appropriate
> improved overview

- pygeometa/templates/iso19139/main.j2
- tests/run_tests.py
- tests/unilingual.mcf
resolves issue #44
this time, retains original GC copyright line [[per PR #45](https://github.com/geopython/pygeometa/pull/45#discussion-diff-64467571)] :)
> correct support for unilingual MCF parameters

- .travis.yml
- README.md
- setup.py
> enable pip install from git

- pygeometa/templates/iso19139-hnap/main.j2
- pygeometa/templates/iso19139/main.j2
- pygeometa/templates/wmo-cmp/main.j2
- tests/nil-identification-language.mcf
- tests/run_tests.py
> implement support for not specifying a language for a dataset (#55)

- pygeometa/__init__.py
- tests/run_tests.py
> support reading from non-file objects (#57)

- README.md
> minor doc improvement, adding = after --output

- doc/MCF_Reference.md
> updated keyword substitution doc

- pygeometa/core.py
- tests/base-distribution.yml
- tests/base-metadata.yml
- tests/child.yml
- tests/run_tests.py
> update base_mcf behaviour (#73)

- README.md
- pygeometa/core.py
> Expose pygeometa log messages when running from the command line (#76)

- doc/MCF_Reference.md
- pygeometa/core.py
> support both date and datetime magic keywords (#81)

- pygeometa/core.py
- tests/bad-version.yml
- tests/child.yml
- tests/missing-version.yml
- tests/nil-identification-language.yml
- tests/run_tests.py
> add MCF version validation (#85)

- doc/MCF_Reference.md
I've updated base_MCF doc so we can close #73
> update doc for MCF nesting

- doc/MCF_Reference.md
I've added documentation on multilangual support so we can close issue #33
> update multilangual support docs

- doc/MCF_Reference.md
I've updated the docs with what is mandatory/optional, see issue #65.
> updated docs for issue #65

- README.md
- doc/wmo-wigos.md
- pygeometa/templates/wmo-wigos/contact.j2
- pygeometa/templates/wmo-wigos/main.j2
- sample-wmo-wigos.yml
- tests/run_tests.py
Adds support for [WMO WIGOS Metadata](http://schemas.wmo.int/wmdr/1.0RC7/documentation/WMDR_ModelAndSchemaSpecification.pdf).
> add support for WMO WIGOS Metadata

- pygeometa/core.py
- tests/dates-pre-1900.yml
- tests/run_tests.py
> add workaround for dates before 1900 (#102)

- pygeometa/core.py
- tests/contact.yml
- tests/deep-nest-child.yml
- tests/deep-nest-parent.yml
- tests/run_tests.py
> fix deep nesting (#104)

- .travis.yml
- pygeometa/core.py
- requirements-dev.txt
- tests/run_tests.py
This PR:
- remove rST generation since PyPI supports Markdown
- fixes pyyaml loading (https://msg.pyyaml.org/load)
> Doc yaml fixes

- pygeometa/templates/wmo-wigos/main.j2
> ensure wmdr:validPeriod is optional

- README.md
- docs/content/tutorial.md
- pygeometa/__init__.py
- pygeometa/core.py
Adds subcommand to provide a high level report on an MCF.
> add subcommand to provide high level info

- docs/content/tutorial.md
- also expand MCF acronym in example (for the fast readers)
> tutorial: fix URL to MCF reference

- docs/content/reference/mcf.md
- pygeometa/core.py
- pygeometa/schemas/iso19139/main.j2
- pygeometa/schemas/iso19139_hnap/main.j2
- pygeometa/schemas/wmo_cmp/main.j2
- sample.yml
- tests/bad-version.yml
- tests/broken-yaml.yml
- tests/dates-pre-1900.yml
- tests/deep-nest-child.yml
- tests/deep-nest-parent.yml
- tests/missing-version.yml
- tests/nil-identification-language.yml
- tests/unilingual.yml
> add capability for generic extent object (#111)

- docs/content/reference/formats/wmo-cmp.md
- docs/content/reference/mcf.md
- pygeometa/helpers.py
- pygeometa/schemas/stac/__init__.py
- tests/run_tests.py
Implements STAC Item output from MCF (#125), plus fixes some docs inconsistencies.
cc @pvgenuchten
> enable a STAC export of mcf (#125)

- docs/content/reference/mcf.md
- pygeometa/schemas/iso19139/main.j2
- pygeometa/schemas/iso19139_2/main.j2
- pygeometa/schemas/iso19139_hnap/main.j2
- pygeometa/schemas/wmo_cmp/main.j2
- sample.yml
Adds support for keyword thesaurus/vocabulary.
> support keyword vocabulary

- README.md
- pygeometa/schemas/__init__.py
- pygeometa/schemas/base.py
- pygeometa/schemas/ogc_api_records/__init__.py
- tests/run_tests.py
This PR adds support for the OGC API Records - Part 1: Core [record model](https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/record.yaml).
> add support for OGC API - Records record model

- MANIFEST.in
- README.md
- debian/control
- docs/content/index.md
- docs/content/reference/formats/iso19139-hnap.md
- docs/content/reference/formats/wmo-wigos.md
- docs/content/reference/mcf.md
- docs/content/tutorial.md
- pygeometa/__init__.py
- pygeometa/cli_options.py
- pygeometa/core.py
- pygeometa/helpers.py
- pygeometa/schemas/iso19139/contact.j2
- pygeometa/schemas/iso19139/main.j2
- pygeometa/schemas/iso19139_2/contact.j2
- pygeometa/schemas/iso19139_2/main.j2
- pygeometa/schemas/iso19139_hnap/contact.j2
- pygeometa/schemas/iso19139_hnap/main.j2
- pygeometa/schemas/mcf/core.yml
- pygeometa/schemas/mcf/iso19139_2.yml
- pygeometa/schemas/mcf/wmo-cmp.yml
- pygeometa/schemas/mcf/wmo-wigos.yml
- pygeometa/schemas/ogc_api_records/__init__.py
- pygeometa/schemas/stac/__init__.py
- pygeometa/schemas/wmo_cmp/contact.j2
- pygeometa/schemas/wmo_cmp/main.j2
- pygeometa/schemas/wmo_wigos/contact.j2
- requirements.txt
- sample.yml
- tests/run_tests.py
Implements #5.  Also updates CLI tooling making specifying an MCF file as an argument (instead of an option).
> Schema validation

- pygeometa/core.py
- pygeometa/schemas/mcf/core.yml
- tests/base-metadata.yml
- tests/child.yml
- tests/run_tests.py
- tests/sample-child.yml
As per https://github.com/geopython/pygeometa/issues/5#issuecomment-962124307
> fix validation of nested MCFs (#5)

- pygeometa/schemas/iso19139/main.j2
- pygeometa/schemas/iso19139_2/main.j2
- pygeometa/schemas/iso19139_hnap/main.j2
> add WMO thesaurus to ISO based keywords

- .github/workflows/main.yml
- debian/control
- docs/content/index.md
- docs/content/tutorial.md
- pygeometa/__init__.py
- pygeometa/cli_options.py
- pygeometa/core.py
- pygeometa/helpers.py
- pygeometa/schemas/__init__.py
- pygeometa/schemas/base.py
- pygeometa/schemas/iso19139/__init__.py
- requirements.txt
- tests/md-SMJP01RJTD-gmd.xml
- tests/run_tests.py
- tests/sample_schema/__init__.py
- tests/urn:x-wmo:md:int.wmo.wis::ISMD01EDZW.xml
Implements first pass for #79.  Note that only the vanilla ISO importer is implemented, but the framework is there to implement importing from other schemas as required.
> add ISO importer (#79)

- docs/content/reference/mcf.md
- pygeometa/schemas/mcf/core.yml
- sample.yml
Implements #159
cc @pvgenuchten
> add support for MCF attributes

- pygeometa/schemas/iso19139/__init__.py
> safeguard from ERRDAP based ISO imports

- pygeometa/schemas/iso19139/main.j2
- pygeometa/schemas/iso19139_2/main.j2
- pygeometa/schemas/iso19139_hnap/main.j2
- pygeometa/schemas/wmo_cmp/main.j2
> fix ISO contact handling (#171)

- pygeometa/schemas/dcat/__init__.py
Belt and suspenders. The output is a bit strange, but it is better to asses that with an RDF validator. Other issues to follow if needed.
> Closes #177

- docs/content/pygeoapi-plugin.md
- docs/mkdocs.yml
- pygeometa/pygeoapi_plugin.py
This PR adds a pygeoapi plugin, which will allow any pygeoapi setup to integrate pygeometa workflow (validate, generate) via OGC API - Processes.
> add pygeoapi plugin

- README.md
- docs/content/pygeoapi-plugin.md
- docs/content/tutorial.md
- pygeometa/__init__.py
- pygeometa/core.py
- pygeometa/pygeoapi_plugin.py
- pygeometa/schemas/ogcapi_records/__init__.py
> add metadata transformation workflow

- pygeometa/schemas/ogcapi_records/__init__.py
- pygeometa/schemas/wmo_wcmp2/__init__.py
> OARec/WCMP2: add default creation date, safeguard temporal

- .github/workflows/main.yml
- pygeometa/schemas/iso19139/__init__.py
- pygeometa/schemas/ogcapi_records/__init__.py
Fixes #210.  Depends on merge of https://github.com/geopython/OWSLib/pull/862 and new release of OWSLib.
> improve ISO import and OARec contact output

- docs/content/reference/mcf.md
- pygeometa/schemas/mcf/core.yaml
- pygeometa/schemas/ogcapi_records/__init__.py
- sample.yml
> add identification.license to MCF model (#205)

- docs/content/reference/mcf.md
- pygeometa/schemas/iso19139/main.j2
- pygeometa/schemas/iso19139_2/main.j2
- pygeometa/schemas/iso19139_hnap/main.j2
- pygeometa/schemas/mcf/core.yaml
- pygeometa/schemas/wmo_cmp/main.j2
Implements #202
cc @pvgenuchten
> add support for spatial keywords (#202)

- pygeometa/schemas/ogcapi_records/__init__.py
pygeometa's contact model allows for 1..n contacts to be defined with the role as a key (reuse is possible via YAML anchors and references).  Example:
```yaml
contact:
pointOfContact: &contact_poc
organization: Environment Canada
url: https://www.ec.gc.ca/
individualname: Tom Kralidis
positionname: Senior Systems Scientist
phone: +01-123-456-7890
fax: +01-123-456-7890
address: 4905 Dufferin Street
city: Toronto
administrativearea: Ontario
postalcode: M3H 5T4
country: Canada
email: foo@bar.tld
hoursofservice: 0700h - 1500h EST
contactinstructions: email
distributor: *contact_poc
```
OGC API - Records allows for 1..n providers.  Each provider can have 1..n roles.
Current OARec generation functionality will result in 2 provider objects with distinct roles:
```json
"providers": [
{
"name": …
```
> OARec: streamline contacts

- pygeometa/core.py
- pygeometa/pygeoapi_plugin.py
- pygeometa/schemas/__init__.py
- pygeometa/schemas/base.py
- pygeometa/schemas/dcat/__init__.py
- pygeometa/schemas/iso19139/__init__.py
- pygeometa/schemas/iso19139_2/__init__.py
- pygeometa/schemas/iso19139_hnap/__init__.py
- pygeometa/schemas/ogcapi_records/__init__.py
- pygeometa/schemas/stac/__init__.py
- pygeometa/schemas/wmo_cmp/__init__.py
- pygeometa/schemas/wmo_wcmp2/__init__.py
- pygeometa/schemas/wmo_wigos/__init__.py
Implements #223 
- adds support for details outlining read/write capabilities of all supported schemas
- exposes via pygeoapi plugin
> add support for detailed schema information (#223)

- pygeometa/schemas/ogcapi_records/__init__.py
> OARec: write keywords as theme/concepts if vocabulary exists

- pygeometa/pygeoapi_plugin.py
Add output kwargs to pygeometa OGC API - Processes to allow pygeoapi to execute the process
https://github.com/geopython/pygeoapi/issues/1901
> Add outputs to OAProc function argument

- pygeometa/schemas/stac/__init__.py
> fix STAC Item provider output (#238)

- README.md
- docs/content/tutorial.md
- pygeometa/core.py
- pygeometa/schemas/__init__.py
- tests/run_tests.py
> add support for import/transform schema autodetection (#198)
